### ISSUE TITLE
Basic 'getting started' doc

### ISSUE THREAD

**Issue by instanceofme** [HBPMedical/PostgresRAW#1]
This seems interesting but people wouldn't know where to start.

Would it be possible to have a quick "getting started" doc (e.g. in the README so that it's displayed in the repository's home page) to perform the most basic tasks ?
- Compile the project (even if it's just to say it's exactly the same steps as compiling PostgreSQL)
- Connect the `psql` client, create a DB (idem)
- Append file(s) as a PostgresRaw "table"

Thanks

**Comment by sambuc** [comment]
Sorry for the long delay, the documentation was improved several time since then. Hopefully 40df390 solve this issue.

Given how old this is I will close it as is for now. Please re-open if this is not satisfactory.

**Comment by instanceofme** [comment]
Thanks!

Not a specific issue, but more of a clarification: assuming `enable_invisible_db` is `on`, if you create a table (e.g. using `psql`), does it use CSV files as storage? or does it use regular postgres files and the raw option is for read only?

**Comment by sambuc** [comment]
OK, so there are several questions here, let me answer them one by one:
 1. **Assuming `enable_invisible_db = on`, if you create a table, does it use CSV as storage?**
    No, unless you follow the steps and add the link to the CSV file in the `conf_file`, by default `snoop.conf`.
   If you don't, then the regular PostgresSQL storage is used, which allows a mixed usage with regular tables and CSV files.

 2. **Is the raw option only for read-only?**
     Yes, the raw option is read-only.

     You can always modify the CSV file, PostgresRAW will invalidate its caches, and see the whole table. If the CSV layout/schema changes, you need to do a `drop table` and recreate it so that the schema matches the new CSV layout.

     We have a user interface which does this automatically: https://github.com/HBPMedical/PostgresRAW-UI, with it all you need is to drop the CSV file in the raw data folder.

     We are packaging both PostgresRAW and the UI as docker images as well:
     * https://github.com/HBPMedical/PostgresRAW-docker
     * https://github.com/HBPMedical/PostgresRAW-UI-docker
